In [6]:
#Considere a matriz  abaixo:
#A=
#[3 2 7]
#[2 5 7]
#[7 1 8]
#Agora, implemente um programa para obter seus:
#a. Autovalores e autovetores
#b. Decomposição SVD

In [4]:
import math
import cmath
import numpy as np

matriz=np.array([[3,2,7],
                [2,5,7],
                [7,1,8]]) 

autovalor, autovetor= np.linalg.eig(matriz)

print("Os autovalores da matriz A são: ")
print(autovalor)
print()
print("Os autovetores da matriz A são: ")
print(autovetor)

Os autovalores da matriz são: 
[14.35631335 -1.47439425  3.11808089]

Os autovetores da matriz são: 
[[-0.49765377 -0.71770766 -0.05354039]
 [-0.58529731 -0.39690103 -0.96038303]
 [-0.64013107  0.57215844  0.27349199]]


In [7]:
import math
import cmath
import numpy as np

matriz=np.array([[3,2,7],
                [2,5,7],
                [7,1,8]])

u,singular,vt= np.linalg.svd(matriz)

print("A matriz original é: ")
print(matriz)
print("A matriz de valores singulares é: ")
print(singular)
print("A matriz de vetores singulares a esquerda é: ")
print(u)
print("A matriz de vetores singulares a direita é: ")
print(vt)

A matriz original é: 
[[3 2 7]
 [2 5 7]
 [7 1 8]]
A matriz de valores singulares é: 
[15.29608356  4.36493456  0.98852112]
A matriz de vetores singulares a esquerda é: 
[[-0.51122121 -0.08505854 -0.85522975]
 [-0.53607734 -0.74623202  0.39466297]
 [-0.67176928  0.66022937  0.33589168]]
A matriz de vetores singulares a direita é: 
[[-0.47778264 -0.28599467 -0.83062073]
 [ 0.6584213  -0.74251922 -0.12307149]
 [ 0.58155407  0.6056998  -0.54306778]]
